security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Main firewall configuration
        main:
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home  # Redirect after login
                enable_csrf: true

            logout:
                path: app_logout
                target: app_home  # Redirect after logout

            provider: app_user_provider

    # User provider to fetch users from the database
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
